describe ("Login into application", async () => {
    it('Prime_testcase1',async ()=>{
        await browser.maximizeWindow()
        await browser.url("https://www.primevideo.com/")
        const profilebtn = await browser.$("//span[text()='Account Menu']")
        await profilebtn.click()
        const signinbtn = await browser.$("//a[@id='pv-nav-sign-in']")
        await signinbtn.click()
        const userid = await browser.$("[id='ap_email']")
        await userid.setValue("teju.sweety1@gmail.com")
        const pwd = await browser.$("//input[@id='ap_password']")
        await pwd.setValue("rooptej8589")
        const submitbtn = await browser.$("//input[@id='signInSubmit']")
        await submitbtn.click()
        const feature = await browser.$("pv-nav-mystuff")
        await feature.click()
     const pagetext = await browser.$("a=Purchases & Rentals")
     console.log(pagetext.getText())
        console.log("******************************************************")
})
})